#!/usr/bin/env python3
"""Physical Isaac Sim 6.1 SH5/HX5 runtime, without importing a ROS Python ABI.

Run with Isaac's python.sh. The composed stage and metadata are generated by
scene_builder.py; this program does not save or modify the source USD files.
The localhost TCP bridge carries newline JSON. Feedback comes from PhysX
articulation/contact tensors, rendered cameras and physics scene queries.
"""
import argparse
import base64
from collections import deque
import io
import json
import logging
import math
from pathlib import Path
import signal
import socket
import time

from control_math import (DRIVE_NAMES, GROUPS, STEER_NAMES, Trajectory,
                          contact_depth_taxels, contact_taxels, finite_vector, rotate_vector,
                          swerve_targets, sample_trajectory_step, trajectory_start_positions,
                          coalesce_trajectory_commands)

LOG = logging.getLogger("hx5_isaac")


def json_safe(value):
    """Strict JSON diagnostics: missing/non-finite native values become null."""
    if value is None or isinstance(value,(str,bool,int)):
        return value
    if hasattr(value,"tolist"):
        return json_safe(value.tolist())
    if isinstance(value,dict):
        return {str(key):json_safe(item) for key,item in value.items()}
    if isinstance(value,(list,tuple)):
        return [json_safe(item) for item in value]
    number=float(value)
    return number if math.isfinite(number) else None


class JsonLineServer:
    """One local ROS sidecar, bounded queues and nonblocking partial writes."""
    MAX_COMMAND_BYTES = 1024 * 1024

    def __init__(self, port=7866):
        self.listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.listener.bind(("127.0.0.1", port))
        self.listener.listen(1)
        self.listener.setblocking(False)
        self.client = None
        self.incoming = bytearray()
        self.current = memoryview(b"")
        self.latest_state = None
        self.responses = deque(maxlen=256)
        self.disconnected = False

    @staticmethod
    def encode(message):
        return (json.dumps(message, separators=(",", ":"), allow_nan=False) + "\n").encode("utf-8")

    def disconnect(self):
        if self.client:
            self.client.close()
            self.disconnected = True
        self.client = None
        self.incoming.clear()
        self.current = memoryview(b"")
        self.latest_state = None
        self.responses.clear()

    def poll(self):
        commands = []
        if self.client is None:
            try:
                self.client, address = self.listener.accept()
                self.client.setblocking(False)
                self.client.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
                LOG.info("ROS sidecar connected: %s", address)
            except BlockingIOError:
                return commands
        for _ in range(16):
            try:
                chunk = self.client.recv(65536)
                if not chunk:
                    self.disconnect()
                    return []
                self.incoming.extend(chunk)
                if len(self.incoming) > self.MAX_COMMAND_BYTES:
                    LOG.error("Closing sidecar with oversized command buffer")
                    self.disconnect()
                    return []
            except BlockingIOError:
                break
            except OSError:
                self.disconnect()
                return []
        while b"\n" in self.incoming:
            line, _, remaining = self.incoming.partition(b"\n")
            self.incoming = bytearray(remaining)
            try:
                command = json.loads(line)
                if not isinstance(command, dict):
                    raise ValueError("command must be a JSON object")
                commands.append(command)
            except (ValueError, UnicodeError) as error:
                self.reply({"kind":"command_result", "ok":False, "message":str(error)})
        self.flush()
        return commands

    def reply(self, message):
        if self.client:
            self.responses.append(self.encode(message))

    def publish(self, state):
        if self.client:
            # Preserve images/scan from a dropped state until the next send.
            # Older joint feedback itself is replaced, preventing stale queues.
            if self.latest_state:
                for channel in ("images", "scan"):
                    if channel not in state and channel in self.latest_state:
                        state[channel] = self.latest_state[channel]
            self.latest_state = state
            self.flush()

    def flush(self):
        if not self.client:
            return
        for _ in range(8):
            if not self.current:
                if self.responses:
                    self.current = memoryview(self.responses.popleft())
                elif self.latest_state is not None:
                    self.current = memoryview(self.encode(self.latest_state))
                    self.latest_state = None
                else:
                    return
            try:
                written = self.client.send(self.current)
                if written == 0:
                    self.disconnect()
                    return
                self.current = self.current[written:]
            except BlockingIOError:
                return
            except OSError:
                self.disconnect()
                return

    def close(self):
        self.disconnect()
        self.listener.close()

    def finish_responses(self, timeout=.2):
        """Finish a partial frame and queued acknowledgements before closing.

        Never replace an already partially transmitted JSON line. Stop
        producing state frames and bound the drain even if a sidecar stalls.
        """
        self.latest_state = None
        deadline = time.monotonic()+timeout
        while self.client and (self.current or self.responses):
            self.flush()
            if not self.current and not self.responses:
                return True
            if time.monotonic() >= deadline:
                return False
            time.sleep(.002)
        return not self.current and not self.responses


class PhysicsRuntime:
    def __init__(self, app, stage_path, metadata, dt=1/120, cameras_enabled=True):
        # Every Isaac/Omniverse import must follow SimulationApp construction.
        import numpy as np
        import omni.physx
        import omni.timeline
        import omni.usd
        from isaacsim.core.api import World
        from isaacsim.core.prims import RigidPrim, SingleArticulation
        from isaacsim.core.simulation_manager import PhysxScene
        from isaacsim.core.utils.stage import open_stage
        from isaacsim.core.utils.types import ArticulationAction
        from pxr import UsdGeom, UsdPhysics

        self.np, self.action_type, self.app = np, ArticulationAction, app
        self.dt = dt
        self.metadata = metadata
        self.robot_path = metadata["robot_prim_path"]
        if not open_stage(str(stage_path)):
            raise RuntimeError(f"Cannot open composed Isaac stage: {stage_path}")
        self.stage = omni.usd.get_context().get_stage()
        self.UsdGeom = UsdGeom
        self.world = World(physics_dt=dt, rendering_dt=1/30, stage_units_in_meters=1,
                           backend="numpy", device="cpu")
        # Target our actual PhysX scene explicitly. Legacy World/manager
        # settings can reset or miss this flag in Isaac 6.1.
        self.physics_scene = PhysxScene(self.stage.GetPrimAtPath('/World/PhysicsScene'))
        self.physics_scene.set_enabled_stabilization(True)
        self.robot = self.world.scene.add(SingleArticulation(
            prim_path=metadata["articulation_root_path"], name="sh5_hx5",
            reset_xform_properties=False))
        self.dynamic_objects = None
        dynamic_paths = metadata.get("dynamic_object_prim_paths", [])
        if dynamic_paths:
            for path in dynamic_paths:
                if not self.stage.GetPrimAtPath(path).HasAPI(UsdPhysics.RigidBodyAPI):
                    raise RuntimeError(f"Reset object is not an existing rigid body: {path}")
            self.dynamic_objects = self.world.scene.add(RigidPrim(
                prim_paths_expr=dynamic_paths, name="reset_objects", reset_xform_properties=False))

        # One view per fingertip makes contact indexing independent of the
        # number of collider shapes on a merged link. Self-contact is excluded.
        self.tip_views = {}
        # Tensor contact filters identify rigid bodies. Scanned goods often
        # have their collider nested several Xforms beneath the body root;
        # passing that Mesh path silently excludes the physical body.
        filters = []
        for path in metadata.get("contact_filter_prim_paths", []):
            prim = self.stage.GetPrimAtPath(path)
            body_path = path
            while prim and not prim.IsPseudoRoot():
                if prim.HasAPI(UsdPhysics.RigidBodyAPI):
                    body_path = str(prim.GetPath())
                    break
                prim = prim.GetParent()
            if body_path not in filters:
                filters.append(body_path)
        if any(path.startswith(self.robot_path + "/") or path == self.robot_path for path in filters):
            raise RuntimeError("Contact filters must exclude the robot")
        tips = metadata.get("contact_tips", {})
        for sensor, tip in tips.items():
            body = tip.get("rigid_body_path", tip.get("body_path", tip.get("prim_path")))
            if body is None:
                candidates = tip.get("prim_paths", [])
                body = candidates[0] if candidates else None
            if not body or not self.stage.GetPrimAtPath(body).HasAPI(UsdPhysics.RigidBodyAPI):
                raise RuntimeError(f"Fingertip {sensor} does not identify an actual rigid body")
            if filters:
                # Sensor views do not belong to Scene's reset registry:
                # Scene.post_reset would try to assign non-root link poses.
                view = RigidPrim(
                    prim_paths_expr=body, name=f"contact_{sensor}", reset_xform_properties=False,
                    track_contact_forces=True, prepare_contact_sensors=True,
                    contact_filter_prim_paths_expr=filters, max_contact_count=4096)
                self.tip_views[sensor] = (view, tip)
        self.world.reset()
        self.physics_scene.set_enabled_stabilization(True)
        for view, _ in self.tip_views.values():
            view.initialize(self.world.physics_sim_view)
        self.names = list(self.robot.dof_names)
        expected = {name for names in GROUPS.values() for name in names} | set(STEER_NAMES) | set(DRIVE_NAMES)
        if set(self.names) != expected or len(self.names) != 63:
            raise RuntimeError(f"Expected official SH5/HX5 63 DOFs; missing={sorted(expected-set(self.names))}, extra={sorted(set(self.names)-expected)}")
        self.indices = {name:index for index, name in enumerate(self.names)}
        self.position_indices = np.array([index for index, name in enumerate(self.names) if name not in DRIVE_NAMES])
        self.steer_indices = np.array([self.indices[name] for name in STEER_NAMES])
        self.drive_indices = np.array([self.indices[name] for name in DRIVE_NAMES])
        props = self.robot.dof_properties
        self.limits = {name:(float(props[index]["lower"]), float(props[index]["upper"]))
                       for index, name in enumerate(self.names) if props[index]["hasLimits"]}
        # The official controller has tighter +/-6.28 steering bounds than
        # the URDF's mechanical limits. Preserve the controller behaviour.
        self.steer_limits = [(max(-6.28,self.limits.get(name,(-6.28,6.28))[0]),
                              min(6.28,self.limits.get(name,(-6.28,6.28))[1])) for name in STEER_NAMES]
        self.initial_positions = np.array(self.robot.get_joint_positions(), dtype=float)
        initial = metadata.get("initial_positions", {})
        if not isinstance(initial, dict):
            raise RuntimeError("Metadata initial_positions must be a joint-name mapping")
        if not set(name for names in GROUPS.values() for name in names).issubset(initial):
            raise RuntimeError("Metadata must explicitly provide the 57 initial joint positions")
        for name, value in initial.items():
            if name in self.indices:
                value = float(value)
                if not math.isfinite(value):
                    raise RuntimeError(f"Non-finite initial joint position: {name}")
                if name in self.limits and not self.limits[name][0]-1e-6 <= value <= self.limits[name][1]+1e-6:
                    raise RuntimeError(f"Initial joint position exceeds {name} limits")
                self.initial_positions[self.indices[name]] = value
        self.initial_root_position, self.initial_root_orientation = self.robot.get_world_pose()
        self.initial_root_position = self.initial_root_position.copy()
        self.initial_root_orientation = self.initial_root_orientation.copy()
        self.robot.set_default_state(position=self.initial_root_position,
                                     orientation=self.initial_root_orientation)
        self.robot.set_joints_default_state(positions=self.initial_positions,
                                            velocities=np.zeros(63), efforts=np.zeros(63))
        self.robot.set_joint_positions(self.initial_positions)
        self.robot.set_joint_velocities(np.zeros(63))
        if self.dynamic_objects:
            self.object_positions, self.object_orientations = self.dynamic_objects.get_world_poses()
            self.object_positions, self.object_orientations = self.object_positions.copy(), self.object_orientations.copy()
            self.dynamic_objects.set_default_state(
                positions=self.object_positions, orientations=self.object_orientations,
                linear_velocities=np.zeros((len(dynamic_paths),3)),
                angular_velocities=np.zeros((len(dynamic_paths),3)))
        # Velocity wheels must not fight a position spring. Keep the builder's
        # force limits/damping but ensure correct control mode per DOF.
        controller = self.robot.get_articulation_controller()
        kp, kd = controller.get_gains()
        kp = np.asarray(kp).reshape(-1).copy()
        kd = np.asarray(kd).reshape(-1).copy()
        kp[self.drive_indices] = 0
        if np.any(kd[self.drive_indices] <= 0):
            raise RuntimeError("Wheel velocity drives require positive damping in scene metadata")
        controller.set_gains(kps=kp, kds=kd, save_to_usd=False)

        self.target_positions = self.initial_positions.copy()
        self.trajectories = {}
        self.base_velocity = (0.,0.,0.)
        self.last_base_command = -math.inf
        self.sequence, self.epoch = 0, 0
        self.shutdown_requested = False
        self.hold_count = 0
        self.last_hold_reason = None
        self.scene_query = omni.physx.get_physx_scene_query_interface()
        self.cameras = {}
        self.camera_local_poses = {}
        if cameras_enabled:
            from isaacsim.sensors.camera import Camera
            camera_metadata = metadata.get("cameras", metadata.get("camera", {}))
            for name, spec in camera_metadata.items():
                camera = Camera(prim_path=spec["prim_path"], name=name,
                                resolution=tuple(spec["resolution"]), frequency=spec.get("frequency_hz", 30))
                camera.initialize()
                if all(field in spec for field in ('fx', 'fy', 'cx', 'cy')):
                    camera.set_opencv_pinhole_properties(
                        cx=spec['cx'], cy=spec['cy'], fx=spec['fx'], fy=spec['fy'], pinhole=[0.0]*12)
                    camera.set_lens_aperture(0.0)
                    cx, cy, fx, fy, _ = camera.get_opencv_pinhole_properties()
                    LOG.info('Camera %s: %s %s, %.1f Hz, rendered K=(%.3f, %.3f, %.3f, %.3f)',
                             name, spec.get('model'), spec['resolution'], spec.get('frequency_hz',30),
                             fx, fy, cx, cy)
                self.cameras[name] = (camera, spec)
                self.camera_local_poses[name] = camera.get_local_pose(camera_axes="usd")
        self.last_images, self.last_scan = -math.inf, -math.inf
        self.last_image_samples, self.last_scan_sample = {}, None
        self.stats = {"frames":0,"image_frames":0,"scan_frames":0,"valid_tip_samples":0,
                      "invalid_tip_samples":0,"commands":0,"resets":0}
        self.timeline = omni.timeline.get_timeline_interface()
        self._timeline_stop = int(omni.timeline.TimelineEventType.STOP)
        self._timeline_pause = int(omni.timeline.TimelineEventType.PAUSE)
        self._timeline_last_state = "playing"
        self._needs_hard_reset = self._hold_after_pause = self._resetting = False
        self._discard_pending_commands = False
        self._timeline_subscription = self.timeline.get_timeline_event_stream().create_subscription_to_pop(
            self.timeline_event, name="hx5_isaac_timeline_lifecycle")
        LOG.info("Physical articulation ready: %s, DOFs=%d, cameras=%d, tactile_tips=%d",
                 metadata["articulation_root_path"], len(self.names), len(self.cameras), len(self.tip_views))

    @property
    def sim_time(self):
        return float(self.world.current_time)

    def hold(self, reason="stop"):
        self.base_velocity = (0.,0.,0.)
        self.last_base_command = -math.inf
        self.trajectories.clear()
        # Sidecar loss stops targets at the *measured* current pose.
        if self.robot.handles_initialized and not (hasattr(self, "timeline") and self.world.is_stopped()):
            positions = self.robot.get_joint_positions()
            if positions is None:
                raise RuntimeError("Valid articulation handles returned no measured hold pose")
            self.target_positions = self.np.array(positions, dtype=float)
        self.hold_count = getattr(self,"hold_count",0)+1
        self.last_hold_reason = reason

    def suspend_timeline(self, state):
        """Discard pending motion without querying invalidated STOP handles."""
        self.base_velocity = (0., 0., 0.)
        self.last_base_command = -math.inf
        self.trajectories.clear()
        self._discard_pending_commands = True
        self._timeline_last_state = state
        self.last_hold_reason = "timeline " + state
        if state == "stopped":
            self._needs_hard_reset = True
            self._hold_after_pause = False
            self.target_positions = self.initial_positions.copy()
        else:
            self._hold_after_pause = True
        LOG.info("Isaac timeline %s; queued motion cleared and feedback suspended", state)

    def timeline_event(self, event):
        if self._resetting:
            return  # World.reset itself emits STOP/PLAY while rebuilding views.
        if event.type == self._timeline_stop:
            self.suspend_timeline("stopped")
        elif event.type == self._timeline_pause:
            self.suspend_timeline("paused")

    def sync_timeline(self):
        """Recover views only after the user resumes PLAY; never resume STOP."""
        if self.world.is_stopped():
            if self._timeline_last_state != "stopped":
                self.suspend_timeline("stopped")
            return False
        if not self.world.is_playing():
            if self._timeline_last_state != "paused":
                self.suspend_timeline("paused")
            return False
        if self._needs_hard_reset or not self.robot.handles_initialized:
            self.reset()
            if not self.robot.handles_initialized:
                raise RuntimeError("World.reset did not restore articulation physics handles")
            LOG.info("Isaac PLAY restored physics views and the configured initial scene")
        elif self._hold_after_pause:
            self.hold("timeline resumed after pause")
            self._hold_after_pause = False
            self._discard_pending_commands = True
        self._timeline_last_state = "playing"
        return True

    def poll_commands(self, server):
        playing = self.sync_timeline()
        discard = self._discard_pending_commands or not playing
        if discard or not playing:
            server.latest_state = None
        if discard:
            server.incoming.clear()
        commands = server.poll()
        allowed = []
        for command in commands:
            if (discard or not playing) and command.get("kind") in ("trajectory", "basevelocity", "base_velocity", "reset"):
                server.reply({"kind":"command_result", "request_id":command.get("request_id"), "ok":False,
                              "message":"Motion/reset discarded across paused/stopped timeline; send again after GUI Play"})
            else:
                allowed.append(command)
        if discard:
            server.incoming.clear()
            self._discard_pending_commands = False
        return playing, allowed

    def inspect(self):
        if hasattr(self, "timeline") and not self.world.is_playing():
            return {"time":self.sim_time,"epoch":self.epoch,
                    "timeline_state":"stopped" if self.world.is_stopped() else "paused",
                    "physics_handles_valid":bool(self.robot.handles_initialized),
                    "pending_trajectory_groups":list(self.trajectories),
                    "message":"Measured feedback is suspended until GUI Play"}
        controller=self.robot.get_articulation_controller()
        kp,kd=controller.get_gains()
        applied=controller.get_applied_action()
        action={key:getattr(applied,key,None) for key in
                ("joint_positions","joint_velocities","joint_efforts","joint_indices")}
        return json_safe({"time":self.sim_time,"epoch":self.epoch,"joint_names":self.names,
                          "timeline_state":"playing","physics_handles_valid":bool(self.robot.handles_initialized),
                          "native_stiffness":kp,"native_damping":kd,
                          "target_positions":self.target_positions,
                          "initial_positions":self.initial_positions,
                          "measured_positions":self.robot.get_joint_positions(),
                          "measured_velocities":self.robot.get_joint_velocities(),
                          "applied_action":action,
                          "metadata_drives":{name:self.metadata.get("joints",{}).get(name,{}).get("drive")
                                             for name in self.names},
                          "hold_count":self.hold_count,"last_hold_reason":self.last_hold_reason,
                          "pending_trajectory_groups":list(self.trajectories),
                          "base_command":self.base_velocity,"last_base_command_time":self.last_base_command})

    def command(self, command, server):
        kind = command.get("kind")
        request_id = command.get("request_id")
        try:
            if (hasattr(self, "timeline") and not self.world.is_playing() and
                    kind in ("trajectory", "basevelocity", "base_velocity", "reset")):
                raise ValueError("Isaac timeline is paused/stopped; press GUI Play before moving or resetting")
            if kind == "inspect":
                try:
                    server.reply({"kind":"command_result","request_id":request_id,"ok":True,
                                  "message":json.dumps(self.inspect(),separators=(",",":"),allow_nan=False)})
                except Exception as error:
                    server.reply({"kind":"command_result","request_id":request_id,"ok":False,
                                  "message":f"Native diagnostics unavailable: {error}"})
                return False
            if kind == "trajectory":
                measured = dict(zip(self.names, self.robot.get_joint_positions()))
                # A streamed replacement continues from the last applied
                # drive command, matching JTC interpolate_from_desired_state.
                # First/new joints and commands after hold/reset start measured.
                start = trajectory_start_positions(
                    measured, self.trajectories.get(command.get("group")),
                    dict(zip(self.names, self.target_positions)))
                trajectory = Trajectory.from_command(command, start, self.sim_time, self.limits)
                self.trajectories[command["group"]] = trajectory
            elif kind in ("basevelocity", "base_velocity"):
                self.base_velocity = finite_vector([command.get("vx",0),command.get("vy",0),
                                                     command.get("w",command.get("wz",0))], 3)
                self.last_base_command = self.sim_time
            elif kind == "reset":
                self.reset()
                # A reset is a transaction boundary; later commands received
                # in the same TCP batch are flushed by the caller.
                server.reply({"kind":"command_result", "request_id":request_id,
                              "ok":True,"message":"Robot and dynamic objects reset",
                              "time":self.sim_time,"epoch":self.epoch})
                return True
            elif kind == "stop":
                self.hold("stop command")
            elif kind == "shutdown":
                self.hold("shutdown command")
                self.shutdown_requested = True
                self.stats["commands"] += 1
                server.reply({"kind":"command_result","request_id":request_id,"ok":True,
                              "message":"Isaac simulator is shutting down"})
                return True
            else:
                raise ValueError(f"Unknown command kind: {kind}")
            self.stats["commands"] += 1
            if request_id is not None:
                server.reply({"kind":"command_result", "request_id":request_id, "ok":True})
        except (ValueError, TypeError, KeyError) as error:
            server.reply({"kind":"command_result", "request_id":request_id,
                          "ok":False, "message":str(error)})
            LOG.warning("Rejected command: %s", error)
        return False

    def reset(self):
        self._resetting = True
        try:
            self._reset_physics()
        finally:
            self._resetting = False
        self._needs_hard_reset = self._hold_after_pause = False
        self._discard_pending_commands = True
        self._timeline_last_state = "playing"

    def _reset_physics(self):
        self.trajectories.clear()
        self.base_velocity = (0.,0.,0.)
        self.last_base_command = -math.inf
        self.world.reset()
        self.physics_scene.set_enabled_stabilization(True)
        for view, _ in self.tip_views.values():
            view.initialize(self.world.physics_sim_view)
        self.robot.set_world_pose(position=self.initial_root_position,
                                  orientation=self.initial_root_orientation)
        self.robot.set_joint_positions(self.initial_positions)
        self.robot.set_joint_velocities(self.np.zeros(63))
        self.robot.set_linear_velocity(self.np.zeros(3))
        self.robot.set_angular_velocity(self.np.zeros(3))
        if self.dynamic_objects:
            self.dynamic_objects.set_world_poses(self.object_positions, self.object_orientations)
            self.dynamic_objects.set_velocities(self.np.zeros((len(self.object_positions),6)))
        self.target_positions = self.initial_positions.copy()
        self.epoch += 1
        self.sequence = 0
        self.last_images = self.last_scan = -math.inf
        self.last_image_samples, self.last_scan_sample = {}, None
        for name, (camera, _) in self.cameras.items():
            camera.post_reset()
            # Camera.post_reset also restores a default *world* transform.
            # Attached sensors must retain the URDF mount's local transform.
            translation, orientation = self.camera_local_poses[name]
            camera.set_local_pose(translation=translation, orientation=orientation,camera_axes="usd")
        self.stats["resets"] += 1
        LOG.info("Reset restored measured-physics robot and dynamic objects, epoch=%d", self.epoch)

    def drive(self):
        np = self.np
        for group, trajectory in list(self.trajectories.items()):
            positions, done = sample_trajectory_step(trajectory, self.sim_time, self.dt)
            for name, position in zip(trajectory.names, positions):
                self.target_positions[self.indices[name]] = position
            if done:
                del self.trajectories[group]
        velocity = self.base_velocity if self.sim_time-self.last_base_command <= 1.0 else (0.,0.,0.)
        measured_steering = self.robot.get_joint_positions(self.steer_indices)
        steering, wheels = swerve_targets(*velocity, measured_steering, self.steer_limits)
        self.target_positions[self.steer_indices] = steering
        self.robot.apply_action(self.action_type(
            joint_positions=self.target_positions[self.position_indices], joint_indices=self.position_indices))
        self.robot.apply_action(self.action_type(joint_velocities=np.array(wheels),
                                                joint_indices=self.drive_indices))

    @staticmethod
    def xyzw(quaternion_wxyz):
        w,x,y,z = quaternion_wxyz
        return [float(x),float(y),float(z),float(w)]

    def tip_pose(self, view, tip):
        positions, orientations = view.get_world_poses()
        position, orientation = list(map(float, positions[0])), self.xyzw(orientations[0])
        # Optional fixed tip-frame offset authored by the URDF importer.
        offset = tip.get("taxel_translation", tip.get("local_position", (0,0,0)))
        rotated = rotate_vector(offset, orientation)
        position = [a+b for a,b in zip(position,rotated)]
        local = tip.get("taxel_orientation_xyzw", (0,0,0,1))
        x,y,z,w = orientation
        a,b,c,d = local
        orientation = [w*a+x*d+y*c-z*b, w*b-x*c+y*d+z*a,
                       w*c+x*b-y*a+z*d, w*d-x*a-y*b-z*c]
        return position, orientation

    def contacts(self):
        result = {"left":{}, "right":{}}
        for side, letter in (("left","l"),("right","r")):
            for finger in range(1,6):
                sensor = f"finger_{letter}_sensor{finger}"
                sample = {"valid":False}
                try:
                    if sensor not in self.tip_views:
                        raise ValueError("Contact backend unavailable")
                    view, tip = self.tip_views[sensor]
                    data = view.get_contact_force_data(dt=self.dt)
                    if data is None or len(data) != 6:
                        raise ValueError("Contact tensor unavailable")
                    forces, points, _, distances, counts, starts = data
                    if counts is None or starts is None or self.np.asarray(counts).size == 0:
                        raise ValueError("Contact filters have no initialized tensor pairs")
                    counts, starts = self.np.asarray(counts), self.np.asarray(starts)
                    if (counts.shape != starts.shape or not self.np.isfinite(counts).all()
                            or not self.np.isfinite(starts).all() or (counts < 0).any()
                            or (starts < 0).any() or (counts != self.np.floor(counts)).any()
                            or (starts != self.np.floor(starts)).any()):
                        raise ValueError("Invalid contact pair counts or offsets")
                    indices = []
                    for count, start in zip(counts.flat, starts.flat):
                        indices.extend(range(int(start), int(start)+int(count)))
                    # The backend's zero-count tensor is a measured, valid
                    # no-contact sample; absent tensors never become zeros.
                    if indices:
                        position, orientation = self.tip_pose(view, tip)
                        measured_points = [list(map(float,points[index])) for index in indices]
                        cells = contact_taxels([float(forces[index][0]) for index in indices],
                                               measured_points,
                                               position, orientation, thumb=finger==1, right=side=="right")
                        depths = contact_depth_taxels([float(distances[index][0]) for index in indices],
                                                       measured_points,position,orientation,
                                                       thumb=finger==1,right=side=="right")
                    else:
                        # No coordinate transform is needed for measured
                        # absence of contact. Keep all ten tensors sampled
                        # every physics tick and retain the original taxels.
                        cells, depths = [0.]*9, [0.]*9
                    sample = {"valid":True,"forces":cells,"penetration_depths":depths}
                    self.stats["valid_tip_samples"] += 1
                except Exception as error:
                    # Tensor handles can become unavailable when a user
                    # pauses/stops the GUI timeline. Report invalid, never a
                    # fabricated zero-pressure sample or a halted simulator.
                    self.stats["invalid_tip_samples"] += 1
                    if self.sequence == 0:
                        LOG.warning("Tactile %s invalid: %s", sensor, error)
                result[side][sensor] = sample
        return result

    def scan(self, position, orientation):
        origin_offset = rotate_vector((0,0,.344), orientation)
        origin = tuple(a+b for a,b in zip(position, origin_offset))
        count, maximum, minimum = 720, 10., .05
        ranges = []
        for index in range(count):
            angle = -math.pi + 2*math.pi*index/count
            direction = tuple(rotate_vector((math.cos(angle),math.sin(angle),0),orientation))
            closest = [maximum+1]
            def report(hit):
                # 6.1 scene queries return RaycastHit objects, not old dicts.
                path = str(getattr(hit,"rigid_body", "") or getattr(hit,"collision", ""))
                if path != self.robot_path and not path.startswith(self.robot_path+"/"):
                    distance = float(hit.distance)
                    if minimum <= distance <= maximum:
                        closest[0] = min(closest[0], distance)
                return True
            self.scene_query.raycast_all(origin, direction, maximum, report, bothSides=True)
            ranges.append(closest[0] if closest[0] <= maximum else None)
        self.stats["scan_frames"] += 1
        return {"ranges":ranges,"angle_min":-math.pi,"angle_max":math.pi-2*math.pi/count,
                "angle_increment":2*math.pi/count,"range_min":minimum,"range_max":maximum,
                "scan_time":.1,"time_increment":0.,"frame_id":"isaac_scan","time":self.sim_time}

    def images(self):
        from PIL import Image
        result = {}
        for name, (camera, spec) in self.cameras.items():
            pixels = camera.get_rgb()
            if pixels is None:
                continue
            pixels = self.np.asarray(pixels)
            if pixels.ndim != 3 or pixels.shape[2] < 3 or pixels.size == 0:
                continue
            if pixels.dtype != self.np.uint8:
                pixels = self.np.clip(pixels*255 if pixels.max() <= 1 else pixels, 0,255).astype(self.np.uint8)
            buffer = io.BytesIO()
            Image.fromarray(pixels[:,:,:3]).save(buffer,format="JPEG",
                quality=spec.get('jpeg_quality',95), subsampling=spec.get('jpeg_subsampling',0))
            result[name] = {"jpeg":base64.b64encode(buffer.getvalue()).decode("ascii"),
                            "width":int(pixels.shape[1]),"height":int(pixels.shape[0]),
                            "frame_id":spec.get("optical_frame",name+"_optical_frame"),"time":self.sim_time}
            if all(field in spec for field in ('fx', 'fy', 'cx', 'cy')):
                cx, cy, fx, fy, _ = camera.get_opencv_pinhole_properties()
                result[name].update(fx=float(fx), fy=float(fy), cx=float(cx), cy=float(cy))
        if result:
            self.stats["image_frames"] += 1
        return result

    def step(self, render):
        if not self.sync_timeline():
            return None
        self.drive()
        # World.step(render=True) advances rendering_dt/physics_dt substeps.
        # Separating these operations guarantees one measured frame per 1/120
        # second; world.render explicitly suspends simulation during rendering.
        self.world.step(render=False)
        if render:
            self.world.render()
        # GUI STOP/PAUSE can occur inside render(), after the pre-step check.
        # Defer all native reads and feedback until the next valid PLAY frame.
        if not self.world.is_playing() or self._needs_hard_reset or not self.robot.handles_initialized:
            return None
        position, orientation_wxyz = self.robot.get_world_pose()
        orientation = self.xyzw(orientation_wxyz)
        positions = self.robot.get_joint_positions()
        velocities = self.robot.get_joint_velocities()
        if positions is None or velocities is None:
            raise RuntimeError("Initialized playing articulation returned no measured joint state")
        measured = [float(value) for value in (*position,*orientation,*positions,*velocities)]
        if any(not math.isfinite(value) for value in measured):
            raise RuntimeError("PhysX returned non-finite measured robot state")
        state = {"kind":"state","time":self.sim_time,"sequence":self.sequence,"epoch":self.epoch,
                 "joint_names":self.names,"positions":[float(v) for v in positions],
                 "velocities":[float(v) for v in velocities],
                 "base_position":[float(v) for v in position],"base_orientation":orientation,
                 "base_linear_velocity":[float(v) for v in self.robot.get_linear_velocity()],
                 "base_angular_velocity":[float(v) for v in self.robot.get_angular_velocity()],
                 "contacts":self.contacts()}
        if self.sim_time-self.last_scan >= .1-1e-8:
            state["scan"] = self.scan(state["base_position"], orientation)
            self.last_scan_sample = state["scan"]
            self.last_scan = self.sim_time
        image_hz = max((spec.get('frequency_hz',30) for _,spec in self.cameras.values()), default=30)
        if render and self.cameras and self.sim_time-self.last_images >= 1/image_hz-1e-8:
            images = self.images()
            if images:
                state["images"] = images
                self.last_image_samples = images
            self.last_images = self.sim_time
        self.sequence += 1
        self.stats["frames"] += 1
        return state


def arguments():
    parser = argparse.ArgumentParser(description=__doc__)
    assets = Path(__file__).resolve().parents[2]/"simulation/isaac/assets/sh5"
    parser.add_argument("--stage",type=Path,default=assets/"logistics_sh5.usda")
    parser.add_argument("--metadata",type=Path,default=assets/"scene_metadata.json")
    parser.add_argument("--port",type=int,default=7866)
    parser.add_argument("--headless",action="store_true",help="Default opens the Isaac GUI")
    parser.add_argument("--max-frames",type=int,default=0,help="Bounded physical smoke run; 0 runs until stopped")
    parser.add_argument("--no-cameras",action="store_true",help="Skip camera rendering for physics diagnostics")
    parser.add_argument("--no-realtime",action="store_true",help="Run faster/slower than wall time without pacing")
    parser.add_argument("--summary",type=Path,help="Write final measured smoke diagnostics JSON")
    args, unknown = parser.parse_known_args()
    # Kit consumes its own settings arguments from sys.argv. Accommodate
    # launcher --portable-root, --/log/file and window/settings overrides.
    for value in unknown:
        if value.startswith("--") and not value.startswith(("--/", "--portable-root", "--ext-folder")):
            parser.error(f"unrecognized argument: {value}")
    return args


def main():
    args = arguments()
    logging.basicConfig(level=logging.INFO,format="%(asctime)s %(levelname)s %(message)s")
    metadata = json.loads(args.metadata.read_text())
    from isaacsim import SimulationApp
    app = SimulationApp({"headless":args.headless,"width":1280,"height":720,
                         "renderer":"RaytracedLighting","anti_aliasing":0,
                         "fast_shutdown":True,"shutdown_watchdog_timeout":30.0})
    server = None
    runtime = None
    stopping = [False]
    def stop_handler(signum, frame):
        stopping[0] = True
    signal.signal(signal.SIGINT,stop_handler)
    signal.signal(signal.SIGTERM,stop_handler)
    last_state = None
    exit_code = 0
    try:
        runtime = PhysicsRuntime(app,args.stage,metadata,cameras_enabled=not args.no_cameras)
        if not args.headless:
            from omni.kit.viewport.utility import get_active_viewport
            viewport = get_active_viewport()
            if viewport and runtime.stage.GetPrimAtPath("/World/Cameras/Overview").IsValid():
                viewport.camera_path = "/World/Cameras/Overview"
        server = JsonLineServer(args.port)
        LOG.info("Isaac physical JSON server listening on 127.0.0.1:%d",args.port)
        frame, next_tick = 0, time.monotonic()
        while app.is_running() and not stopping[0] and (not args.max_frames or frame < args.max_frames):
            playing, commands = runtime.poll_commands(server)
            commands = coalesce_trajectory_commands(commands, runtime.limits)
            if server.disconnected:
                runtime.hold("sidecar disconnected")
                server.disconnected = False
            for command in commands:
                if runtime.command(command,server):
                    server.incoming.clear()
                    server.latest_state = None
                    break
            if runtime.shutdown_requested:
                if not server.finish_responses(timeout=.2):
                    LOG.warning("Shutdown acknowledgement drain reached its 0.2 second limit")
                LOG.info("Guarded sidecar shutdown requested; closing Isaac without resetting the stage")
                break
            if not playing:
                server.flush()
                runtime.world.render()  # Refresh GUI with physics stepping disabled.
                next_tick = time.monotonic()
                time.sleep(.01)
                continue
            # 30 Hz rendering keeps the GUI responsive and supplies 30 Hz
            # camera frames, while simulation/state sampling remains 120 Hz.
            state = runtime.step(render=(frame % 4 == 0))
            if state is None:
                server.latest_state = None
                next_tick = time.monotonic()
                continue
            last_state = state
            server.publish(state)
            frame += 1
            if not args.no_realtime:
                next_tick += runtime.dt
                delay = next_tick-time.monotonic()
                if delay > 0:
                    time.sleep(min(delay,runtime.dt))
                elif delay < -.25:
                    next_tick = time.monotonic()
        if runtime:
            summary = {"stats":runtime.stats,"last_state":last_state,
                       "last_images":runtime.last_image_samples,"last_scan":runtime.last_scan_sample,
                       "initial_base_position":runtime.initial_root_position.tolist(),
                       "initial_joint_positions":runtime.initial_positions.tolist()}
            if args.summary:
                args.summary.write_text(json.dumps(summary,indent=2,allow_nan=False)+"\n")
            LOG.info("Physical runtime completed: %s",runtime.stats)
    except Exception:
        exit_code = 1
        LOG.exception("Physical runtime failed")
        raise
    finally:
        if runtime:
            try:
                runtime.hold("runtime shutdown")
            except Exception:
                LOG.debug("Physics handles already closed during shutdown",exc_info=True)
        if server:
            server.close()
        # Isaac 6.1 fast shutdown otherwise defaults to exit status zero,
        # even while unwinding an exception. Preserve failures explicitly.
        app.close(wait_for_replicator=False,exit_code=exit_code)


if __name__ == "__main__":
    main()
